var gulp = require('gulp');
var gutil = require('gulp-util');
var bower = require('bower');
var concat = require('gulp-concat');
var sass = require('gulp-sass');
var minifyCss = require('gulp-minify-css');
var rename = require('gulp-rename');
var sh = require('shelljs');
var replace = require('gulp-replace-task');
var args = require('yargs').argv;
var fs = require('fs');
var inject = require('gulp-inject');
var minifyHtml = require('gulp-minify-html');
var ngTemplate = require('gulp-ng-template');

gulp.task('templates:www', function() {
	gulp.src('./www/templates/**/*.html')
		.pipe(minifyHtml({empty: true, quotes: true}))
		.pipe(ngTemplate({
			moduleName: 'app.templates',
			standalone: true,
			filePath: 'autogenerated/templates.js'
		}))
		.pipe(gulp.dest('www'));  // output file: 'dist/js/templates.js'
});

gulp.task('index', function () {
	var target = gulp.src('./www/index.html');
	var sources = gulp.src(['./www/js/**/*.js'], {read: false});

	return target.pipe(inject(sources, {relative: true}))
		.pipe(gulp.dest('./www'));
});

var paths = {
	sass: ['./scss/**/*.scss']
};

gulp.task('default', ['sass', 'index', 'templates:www']);

gulp.task('sass', function(done) {
	gulp.src('./scss/ionic.app.scss')
		.pipe(sass())
		.on('error', sass.logError)
		.pipe(gulp.dest('./www/css/'))
		.pipe(minifyCss({
			keepSpecialComments: 0
		}))
		.pipe(rename({ extname: '.min.css' }))
		.pipe(gulp.dest('./www/css/'))
		.on('end', done);
});

gulp.task('watch', function() {
	gulp.watch(paths.sass, ['sass', 'index']);
});

gulp.task('install', ['git-check'], function() {
	return bower.commands.install()
		.on('log', function(data) {
			gutil.log('bower', gutil.colors.cyan(data.id), data.message);
		});
});

gulp.task('git-check', function(done) {
	if (!sh.which('git')) {
		console.log(
			'  ' + gutil.colors.red('Git is not installed.'),
			'\n  Git, the version control system, is required to download Ionic.',
			'\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
			'\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.'
		);
		process.exit(1);
	}
	done();
});
