# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='location',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
