# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160914_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
