# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160921_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
