# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20161009_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
