# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 13:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20161130_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
