# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20160914_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='class',
            name='sessions_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='sessions_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
