# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20160915_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='session_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 12, 32, 42, 324526)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classsession',
            name='session_start',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 15, 12, 32, 50, 387521)),
            preserve_default=False,
        ),
    ]
