# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20160915_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
