# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0009_auto_20160917_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='checked_in',
            field=models.ManyToManyField(blank=True, related_name='checked_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsessionnotification',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
