# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_auto_20160917_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
