# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20160921_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
