# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_auto_20160922_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_minutes',
            field=models.IntegerField(choices=[(0, '00'), (15, '15'), (30, '30'), (45, '45')]),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_minutes',
            field=models.IntegerField(choices=[(0, '00'), (15, '15'), (30, '30'), (45, '45')]),
        ),
    ]
