# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
